name: Firebase Deploy Debug

on:
  workflow_dispatch:
    inputs:
      do_deploy:
        description: 'Set to true to run deploy steps'
        required: false
        default: 'false'
      channel:
        description: 'Channel name for preview'
        required: false
        default: 'pr-debug'

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Minimal run to verify runner
        run: |
          echo "Runner check OK"
          echo "GITHUB_REF=$GITHUB_REF"
          echo "GITHUB_SHA=$GITHUB_SHA"
          echo "FIREBASE_SERVICE_ACCOUNT exists=$( [ -n "${{ secrets.FIREBASE_SERVICE_ACCOUNT_NEW_ORDER_NAVIGATOR }}" ] && echo true || echo false )"
          echo "Firebase_cli exists=$( [ -n "${{ secrets.Firebase_cli }}" ] && echo true || echo false )"
          echo "FIREBASE_TOKEN exists=$( [ -n "${{ secrets.FIREBASE_TOKEN }}" ] && echo true || echo false )"
